### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by shrekmaxi** [d4l3k/WebSync#170]

**Comment by shrekmaxi** [comment]
Hello Boss, I am a Newbie here, I just hava a stupid question:
Need everyone who wants to use this project  get ready with Redis and Postgresql before the implementation? if so, is there any .sql file should be import into the Postgresql? thanks.

**Comment by d4l3k** [comment]
When you launch the ruby part of WebSync it automatically sets up the database. All you need is a very bare bones installation of Redis and Postgres.
