### ISSUE TITLE
Database configuration

### ISSUE THREAD

**Issue by shrekmaxi** [d4l3k/WebSync#171]
Hi, sorry for bothering again.
I am still stuck with the Database Configuration

> // Database Configuration
"postgres": "postgres:@localhost/websync",
"redis": {
  "host": null,
  "port": null,
  "password": null
},

As your original config.json defined the format of DB connection. Should I   leave the user postgres' password  empty? And actually I just need to configure redis? 
Thanks

**Comment by d4l3k** [comment]
I'd you don't have a password, you don't have to provide it in the
connection string. It depends on how you configured your db.

**Comment by shrekmaxi** [comment]
After I ran rackup, I got this error:
 FATAL:  Ident authentication failed for user "postgres" (PG::ConnectionBad)
bash: syntax error near unexpected token `('


I am sure the user postgres' password is null.

**Comment by shrekmaxi** [comment]
I just figured it out. anyway, thanks again.
it's a great project!
